using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;

namespace AmbulanceSystem.Controls.DataGridControls
{
    /// <summary>
    /// Interaction logic for DataGridControl.xaml
    /// </summary>
    public partial class DataGridControl : UserControl
    {
        public DataGridControlElement DataGridControlElement { get; set; }

        private DataGridControl(DataGridControlElement dataGridControlElement) : base()
        {
            InitializeComponent();
            DataGridControlElement = dataGridControlElement;
            DataGridControlElement.DataGrid = DataGrid;
            DataGridControlElement.PageInfo = PageInfo;
            InitializeButtons();
        }

        public static async Task<DataGridControl> CreateDataGridControl(DataGridControlElement element)
        {
            DataGridControl control = new DataGridControl(element);
            await control.DataGridControlElement.Show();
            return control;
        }

        private void InitializeButtons()
        {
            //Helpers.ButtonContentHelper.SetContent(First, language.FirstPageButton);
            //Helpers.ButtonContentHelper.SetContent(Last, language.LastPageButton);
            //Helpers.ButtonContentHelper.SetContent(Backwards, language.BackwardsButton);
            //Helpers.ButtonContentHelper.SetContent(Forward, language.ForwardButton);

        }

        private async void Last_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElement.Last_Click(sender, e);
        }

        private async void Forward_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElement.Forward_Click(sender, e);
        }

        private async void Backwards_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElement.Backwards_Click(sender, e);
        }

        private async void First_Click(object sender, RoutedEventArgs e)
        {
            await DataGridControlElement.First_Click(sender, e);
        }


        private void DataGrid_AutoGeneratedColumns(object sender, System.EventArgs e)
        {
            DataGridControlElement.InitializeColumns();
        }

        public void ClearSelectedItems()
        {
            for (int i = 0; i < DataGrid.SelectedItems.Count; ++i)
                DataGrid.SelectedItems.RemoveAt(i);
        }

        public async void Refresh()
        {
            await DataGridControlElement.Refresh();
        }
    }
}
